server:
  port: 8080
  servlet:
    context-path: /identity   #su dung khi co nhieu microservice, thi se tim su dung dung path nay de tim kiem

spring:
  datasource:
    url: ${DBMS_CONNECTION:jdbc:mysql://localhost:3306/identity_service}  #cau hinh trong bien moi truong neu khong co thi lay gia tri mac dinh o dang sau dau ":"
    driverClassName: "com.mysql.cj.jdbc.Driver"
    password: ${DBMS_PASSWORD:root} #cau hinh trong bien moi truong neu khong co thi lay gia tri mac dinh o dang sau dau ":"
    username: ${DBMS_USERNAME:root} #cau hinh trong bien moi truong neu khong co thi lay gia tri mac dinh o dang sau dau ":"
  jpa:
    hibernate:
      ddl-auto: update    #tu dong tao table
    show-sql: true
jwt:
  signerKey: "T0swToWRvTU77Vb/O/pEJwNIxk0K+m8J0tSp/1leawO/pqu7dW7S64YZHgGlv6xI"
  valid-duration: 3600 # in second
  refreshable-duration: 36000 # in seconds